# Site settings
title: Julio Goldschmidt blog
email: 
description: "Utilidades diversas"
baseurl: ""
url: "http://juliogold.github.io"
twitter_username: JulioGold
github_username:  JulioGold

# Build settings
markdown: redcarpet
permalink: pretty
